### ISSUE TITLE
Final deployment

### ISSUE THREAD

**Issue by ktohalloran** [azavea/raster-vision-website2#36]
This is a card for tracking the tasks that should be accomplished as a part of the final deployment (credit for task list to @BryanQuigley). Additional cards may be added if necessary.

- [x] Alert the Raster Vision team about possible downtime
- [x] Switch DNS to point to GitHub pages, see reference [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)
- [x] Enable GitHub pages to serve site from custom domain
- [x] Wait for certs to be generated
- [x] Fix anything that breaks
- [x] Turn off old Netlify site
- [x] Archive old site's repo

**Comment by BryanQuigley** [comment]
Got rastervision.org and rastervision.io mixed up - because I really didn't expect them to be in completely different registrars.

Some notes:
Previous DNS servers were:
dns1.p07.nsone.net
dns2.p07.nsone.net
dns3.p07.nsone.net
dns4.p07.nsone.net

@ 10800 IN SOA ns1.gandi.net. hostmaster.gandi.net. 1525703257 10800 3600 604800 10800
@ 10800 IN A 217.70.184.38

reset redirect from  rastervision.org -> rastervision.io

**Comment by BryanQuigley** [comment]
Took a few more steps as it wanted a CNAME for www.rastervision.io.. but I'm not sure we care about that.

Going to confirm everything is fine tomorrow. 

I did notice in the contact bit that Last Name seems to be over some text .  Not sure if that was just missed?  I can't figure out how this domain change would have done that.

**Comment by ktohalloran** [comment]
Thanks for doing this @BryanQuigley! It seems to be working well and looks great! As for the Last Name thing you mentioned, good catch! That's not appearing on Chrome, but is appearing on Firefox. I'll add a new issue to address today.

**Comment by BryanQuigley** [comment]
Added docs.rastervision.io back as well
